### ISSUE TITLE
New account creation, login, guest/demo login.

### ISSUE THREAD

**Issue by pichumy** [pichumy/Mediacord#2]
- [x] Users can log in, sign out, sign up, as well as demo without logging in.
- [x] Users can't access any part of the site without a session.
- [x] Adequate Styling
- [x] Smooth bug-free navigation
- [x] Seeded

**Comment by eshoule** [comment]
Dan, complete the following, and then I will close this issue.
- [x] Going to a random route /#/oweiniouewbrviuwebv should redirect to either /, /login, or /signup.
- [x] Errors should display for both signup and login.
- [x] Errors should clear when moving between signup and login.
- [x] After login should not be able to visit /login

**Comment by eshoule** [comment]
Good job!
